# Generated by Django 5.0.4 on 2024-04-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subfamily', models.CharField(choices=[('Fringillinae', 'Fringillinae'), ('Carduelinae', 'Carduelinae'), ('Euphoniinae', 'Euphoniinae'), ('Unknown', 'Unknown')], default='Unknown', max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('habitat', models.CharField(choices=[('Woodlands', 'Woodlands'), ('Mountains', 'Mountains'), ('Deserts', 'Deserts'), ('Unknown', 'Unknown')], default='Woodlands', max_length=100)),
            ],
        ),
    ]
